name: cmake_raspberry_build

on:
  push:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'
  pull_request:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: AutoModality/action-clean@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Run arm build
      uses: pguyot/arm-runner-action@v1
      id: arm_runner_tests
      with:
        image_additional_mb: 4096
        base_image: 'raspios_lite:2021-05-07'
        cpu: 'arm1176'
        optimize_image: no
        copy_artifact_path: 'cmake_*_armhf.deb'
        commands: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y libconfuse-dev liblo-dev build-essential wget libssl-dev checkinstall
          version=$(cat buildversion)
          wget https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version.tar.gz
          tar xzf cmake-$version.tar.gz
          cd cmake-$version
          sudo ./bootstrap -- -DCMAKE_BUILD_TYPE:STRING=Release
          sudo make -j$(nproc) 
          sudo checkinstall -y -D make install
          sudo mv cmake_*_armhf.deb ../
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: cmake
        path: cmake_*_armhf.deb
        retention-days: 1




    # - name: make release
    #   if: ${{ (startsWith(github.ref, 'refs/tags/v')) && (!(contains(github.ref, '-beta'))) }}
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: |
    #       ./build/volumehidtoosc_*.deb
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    # - name: make release
    #   if: ${{ (startsWith(github.ref, 'refs/tags/v')) && ((contains(github.ref, '-beta'))) }}
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     prerelease: true
    #     files: |
    #       ./build/volumehidtoosc_*.deb
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   