name: cmake_raspberry_build

on:
  push:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'
  pull_request:
    branches: 
    - main
    tags: [ v**]
    paths:
    - '**'
    - '!Docs/**'
    - '!README.md'

jobs:
  build:
    runs-on: self-hosted
    steps:
    # - uses: AutoModality/action-clean@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Run arm build
      uses: pguyot/arm-runner-action@v1
      id: arm_runner_tests
      with:
        image_additional_mb: 4096
        base_image: 'raspios_lite:2021-05-07'
        cpu: 'arm1176'
        optimize_image: no
        copy_artifact_path: 'cmake_*_armhf.deb'
        commands: |
          echo hallo
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: cmake
        path: cmake_*_armhf.deb
        retention-days: 1


    # - name: make release
    #   if: ${{ (startsWith(github.ref, 'refs/tags/v')) && (!(contains(github.ref, '-beta'))) }}
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: |
    #       ./build/volumehidtoosc_*.deb
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    # - name: make release
    #   if: ${{ (startsWith(github.ref, 'refs/tags/v')) && ((contains(github.ref, '-beta'))) }}
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     prerelease: true
    #     files: |
    #       ./build/volumehidtoosc_*.deb
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   